version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    groups:
      github-actions-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      github-actions-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
